spring:
  application:
    name: AWS

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:~/test'
    username: sa
    password: 1234

    h2:
      console:
        enabled: true
        path: /h2-console

#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/AWS?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: 12345678
#
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: false

